repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "120", "--project", "translations_parser"]
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - 'flake8-debugger==4.0.0'
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
        args: ["--line-length", "120"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: mixed-line-ending
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: mixed-line-ending
